name: Check CHANGELOG tags
on:
    pull_request_target:
        types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled, edited ]

jobs:
    test:
        name: Check CHANGELOG tags
        runs-on: ubuntu-latest

        steps:
            - name: test
              uses: nadena-dev/nadena-dev-changelog/check-issue-description@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
