name: Check CHANGELOG tags
on: pull_request


jobs:
    test:
        name: test
        runs-on: ubuntu-latest

        steps:
            - name: test
              uses: nadena-dev/nadena-dev-changelog/check-issue-description@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
